stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/CarPrice.csv
    outs:
    - data/raw/CarPrice.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/CarPrice.csv
    outs:
    - data/processed/train_CarPrice.csv
    - data/processed/test_CarPrice.csv 